CREATE SEQUENCE CHEQUE_ID_SEQ START WITH 1;

CREATE TABLE CHEQUE (
  CHEQUE_ID INT DEFAULT CHEQUE_ID_SEQ.nextval NOT NULL,
  DOLLAR INTEGER NOT NULL,
  CENT INTEGER NOT NULL,
  RECIPIENT VARCHAR(255) NOT NULL,
  PAYMENT_DATE DATE NOT NULL,
  AMOUNT_DESC VARCHAR(255),
  ROWADDDT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  ROWUPDDT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (CHEQUE_ID));

CREATE INDEX IDX_RECIPIENT ON CHEQUE(RECIPIENT);

