version: '2'
services:
  mysql:
    image: mysql:8
#    build: ./mysql/
#    volumes:
#      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=FINANCE
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_CONTAINER_NAME=mysql
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  cheque:
    build: ./cheque-service/
    ports:
      - ${SERVICE_PORT}:${CHEQUE_PORT}
    links:
      - mysql
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - CHEQUE_VERSION=${CHEQUE_VERSION}
      - CHEQUE_PORT=${CHEQUE_PORT}
