version: '2'
services:
  mysql:
    image: mysql:5.7
#    build: ./mysql/
#    volumes:
#      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=FINANCE
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_CONTAINER_NAME=mysql
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  cheque:
    build: ./cheque-service/
    ports:
      - "8080:8080"
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - CHEQUE_VERSION=${CHEQUE_VERSION}
