version: '2'
services:
  mysql:
#    image: mysql:5.6.30
    build: ./mysql/
#    volumes:
#      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=FINANCE
      - DB_USER=root
      - DB_PASS=root
      - MYSQL_ROOT_PASSWORD=root

  cheque:
    build: ./cheque-service/
    ports:
      - "8080:8080"
    links:
      - mysql
    depends_on:
      - mysql

