version: '2'
services:
  mysql:
    image: mysql:5.7
#    build: ./mysql/
#    volumes:
#      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=FINANCE
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_CONTAINER_NAME=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root


  cheque:
    build: ./cheque-service/
    ports:
      - "8080:8080"
    links:
      - mysql
    depends_on:
      - mysql

